### ISSUE TITLE
Add Django 2.1 compatibility

### ISSUE THREAD

**Issue by claudep** [mgrouchy/django-stronghold#75] opened 2018-11-20 10:36 UTC
The test suite is failing with Django 2.1, as it seems that `set_view_func_public` may now receive the `dispatch` method itself in parameter.
I tracked this issue to this Django commit: https://github.com/django/django/commit/fdc936c9130cf4fb5d59869674b9a31cc79a7999

**Comment by abrahammartin** [comment] 2019-02-19 17:35
I'm having the same issue with Django 2.1 and django-stronghold

`
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 44, in _wrapper
    bound_method = dec(bound_method)
  File "/usr/local/lib/python3.7/site-packages/stronghold/decorators.py", line 13, in public
    set_view_func_public(orig_func)
  File "/usr/local/lib/python3.7/site-packages/stronghold/utils.py", line 13, in set_view_func_public
    setattr(func, 'STRONGHOLD_IS_PUBLIC', True)
AttributeError: 'method' object has no attribute 'STRONGHOLD_IS_PUBLIC'
`

**Comment by cw0102** [comment] 2019-03-13 18:14
I was able to get it working with the workaround in #76 but not 100% certain this is the best way to approach it.

**Comment by claudep** [comment] 2019-03-13 19:43
@cjerdonek, would you mind giving your lights on the #76 way of decorating views?

**Comment by cjerdonek** [comment] 2019-03-13 21:23
Sure. I don’t see the test failures though. Which case(s) are failing / not working for you? Is it all views under 2.1 or only views that were defined a certain way or having certain characteristics?

**Comment by cw0102** [comment] 2019-03-19 19:34
Hi @cjerdonek ,

The issue occurs when using either StrongholdPublicMixin or decorating a dispatch method directly with "@method_decorator(public)" because in Django 2.1, the decorator will receive the bound method dispatch which cannot have attributes set instead of a wrapped function. The workaround in #76 just creates a wrapper for the bound method for the purposes of settings attributes, but it also messes with the function partial wrapper on the function itself, and I don't know if this will cause any issues or if there is a better way to approach it.

**Comment by cw0102** [comment] 2019-04-12 15:19
Looking at https://github.com/django/django/commit/f434f5b84f7fcea9a76a551621ecce70786e2899#diff-2b7369f3709089e3ebcfdd6a4d3e3787 this regression fix should solve the problem. I'll look into a better way to make use of this when I get some time.

**Comment by cjerdonek** [comment] 2019-04-13 02:55
Sorry I wasn’t able to make time to look at this yet. (I agree that it’s hard to understand what this code is doing, which I know from working on it.) I will see if I can at some point.

**Comment by cw0102** [comment] 2019-04-15 18:26
The problem in django-stronghold is that the stronghold code is [stripping off functools partial wrappers](https://github.com/mgrouchy/django-stronghold/blob/master/stronghold/decorators.py#L11-L12) (I assume to play nice with other decorators? Not entirely sure here, this is what I was fuzzy on, there is a test [here](https://github.com/mgrouchy/django-stronghold/blob/master/stronghold/tests/testdecorators.py#L32-L39) that specifically checks the partials have been removed) and [the regression fix for setting attributes on bound methods uses a functools partial](https://github.com/django/django/blob/stable/2.1.x/django/utils/decorators.py#L38-L42).

I took another attempt at fixing this in #76 which seems to play nice with additional partials and make use of the existing code in django. This is largely stabbing in the dark as I am not entirely knowledgeable about python/django internals, but it seems to work and pass tests on all the compatible versions.

**Comment by cjerdonek** [comment] 2019-04-16 07:35
Have you confirmed if this is an issue in both Django 2.1 and Django 2.2, or just Django 2.1? The reason is that the regression fix you linked to above (https://github.com/django/django/pull/9819) that I wrote landed in Django 2.2, so I'm wondering if you're simply hitting the regression in Django 2.1.

**Comment by cjerdonek** [comment] 2019-04-16 07:41
The traceback in this comment: https://github.com/mgrouchy/django-stronghold/issues/75#issuecomment-465233183
suggests that you're hitting the regression. See here for the original report from Django REST Framework, which matches yours: https://github.com/encode/django-rest-framework/pull/6043

**Comment by cw0102** [comment] 2019-04-16 21:06
Huge thanks for checking this out. I can confirm that django-stronghold does not work on 2.1 or 2.2 without modification due to a small breaking change in how the functions are wrapped (as part of the regression fix and the changes to decorators in general). The regression fix for decorators also seems to exist in the 2.1.x branch for django as well as 2.2.x.

#76 seems to be working on all current versions, but I'd appreciate a review by anyone else involved with this repo to push it along or make changes as necessary 😃

**Comment by mgrouchy** [comment] 2020-01-15 03:56
This is resolved.

**Closed by mgrouchy** 2020-01-15 03:56 UTC
